[project]
name = "dep-inj"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi",
]

[tool.uv.workspace]
members = ["fastapi"]

[tool.uv.sources]
fastapi = { workspace = true }
